# Generated by Django 4.2.3 on 2023-07-28 15:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decl_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decl_status', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Статус декларации',
                'verbose_name_plural': 'Статус декларации',
            },
        ),
        migrations.CreateModel(
            name='Decl_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_decl', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Тип декларации',
                'verbose_name_plural': 'Тип декларации',
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('company_contact_person', models.CharField(max_length=100, null=True)),
                ('company_phone', models.CharField(max_length=100, null=True)),
                ('company_mail', models.EmailField(max_length=254, null=True)),
                ('company_declpacked', models.IntegerField(null=True)),
                ('company_ecp', models.BooleanField(null=True)),
                ('company_ecp_decl', models.CharField(max_length=100, null=True)),
                ('company_ecp_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Компании',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='Payment_invoice_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decl_status', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Статус счета',
                'verbose_name_plural': 'Статус счета',
            },
        ),
        migrations.CreateModel(
            name='Decl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decl_number', models.IntegerField(null=True, verbose_name='№ декларации')),
                ('decl_code_quantity', models.IntegerField(null=True)),
                ('decl_car_number', models.CharField(max_length=100)),
                ('decl_car_quantity', models.IntegerField(null=True)),
                ('decl_price', models.IntegerField(null=True)),
                ('decl_comment', models.TextField(null=True)),
                ('decl_greatdate', models.DateField(default=datetime.date.today)),
                ('decl_company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ebdecl.firm', verbose_name='Название компании')),
                ('decl_plament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ebdecl.payment_invoice_status')),
                ('decl_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ebdecl.decl_status')),
                ('decl_tipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ebdecl.decl_type')),
            ],
            options={
                'verbose_name': 'Декларации',
                'verbose_name_plural': 'Декларации',
                'ordering': ['decl_greatdate', 'decl_company_name'],
            },
        ),
    ]
