# Generated by Django 4.2.3 on 2023-07-28 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebdecl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decl',
            name='decl_greatdate',
            field=models.DateField(default=datetime.date(2023, 7, 28)),
        ),
    ]
